### ISSUE TITLE
Missing module exif

### ISSUE THREAD

**Issue by rts58** [gpetersen/MMM-BackgroundSlideshowInfo#1]
I gave it a quick try under windows, haven't tried on pi yet.  I'm sure I've missed something but upon adding this module I am getting error that it is looking for module exif.

**Comment by gpetersen** [comment]
Ahh, I forgot, in your MMM-BackgroundSlideshowInfo dir, run:
npm install exif

**Comment by rts58** [comment]
Awesome, working now! A couple comments so far: Is there a way to insert some type of delimiter in the place names?  For now it looks like this: "Veterans Memorial ParkUSNew Hampshire".  Also if the picture is followed by an image with no EXIF data the EXIF data remains instead of being cleared.

**Comment by gpetersen** [comment]
Great, closing this issue, opening others to track the additional comments.
