### ISSUE TITLE
no Exif, server IP inserted

### ISSUE THREAD

**Issue by rts58** [gpetersen/MMM-BackgroundSlideshowInfo#4]
I put this on my RPi.  The images continue to work fine, however no EXIF data is being pulled.  Here is example of consol output.  For some reason `http://0.0.0.0:8080/` is inserted in the link after MM.
```
[BACKGROUNDSLIDESHOWINFO] GET_EXIF - url: http://0.0.0.0:8080/modules/MMM-BackgroundSlideshow/exampleImages/BARN%20PARTY%20003.JPG
[BACKGROUNDSLIDESHOWINFO] helper loading EXIF data for /home/pi/MagicMirror/http://0.0.0.0:8080/modules/MMM-BackgroundSlideshow/exampleImages/BARN PARTY 003.JPG
Error: Encountered the following error while trying to read given image: Error: ENOENT: no such file or directory, open '/home/pi/MagicMirror/http://0.0.0.0:8080/modules/MMM-BackgroundSlideshow/exampleImages/BARN PARTY 003.JPG'

```
I just noticed you had some comments about this in node_helper.  If I insert this line 28: `var imageUri = imageUri.replace("http://0.0.0.0:8080/","");`  it fixes this issue.

**Comment by gpetersen** [comment]
Thanks for this!  Fixed.
